"""
Consolidated schemas package.

IMPORTANT: Explicit imports only - no wildcards to prevent circular imports.
"""

# Auth schemas
from app.schemas.auth import (
    Industry,
    ProfessionalSubcategory,
    RevenueRange,
    Currency,
    SignupRequest,
    LoginRequest,
    UserAuthInfo,
    DemoLoginRequest,
    AuthResponse,
    ForgotPasswordRequest,
    ForgotPasswordResponse,
    ResetPasswordRequest,
    ChangePasswordRequest,
    BusinessProfileRequest,
    BusinessProfileResponse,
)

# User schemas
from app.schemas.user import (
    UserCreate,
    UserResponse,
)

# Treasury schemas (clients, expenses, balances)
from app.schemas.treasury import (
    CashAccountCreate,
    CashAccountResponse,
    CashPositionCreate,
    CashAccountsUpdate,
    CashPositionResponse,
    ClientCreate,
    ClientResponse,
    ClientUpdate,
    ClientCreateForOnboarding,
    ClientWithEventsResponse,
    ExpenseBucketCreate,
    ExpenseBucketResponse,
    ExpenseBucketUpdate,
    ExpenseBucketCreateForOnboarding,
    ExpenseBucketWithEventsResponse,
)

# Obligation schemas
from app.schemas.obligation import (
    ObligationAgreementCreate,
    ObligationAgreementUpdate,
    ObligationAgreementResponse,
    ObligationScheduleCreate,
    ObligationScheduleUpdate,
    ObligationScheduleResponse,
    PaymentEventCreate,
    PaymentEventUpdate,
    PaymentEventResponse,
    ObligationWithSchedules,
    ObligationWithPayments,
    ObligationFull,
)

# Forecast schemas
from app.schemas.forecast import (
    ForecastEventSummary,
    ConfidenceBreakdown,
    WeekConfidenceBreakdown,
    WeekForecast,
    ForecastSummary,
    ConfidenceCountBreakdown,
    ForecastConfidence,
    ForecastResponse,
    ForecastResponseV1,
    MetricValue,
    ScenarioBarMetrics,
    ScenarioBarResponse,
    TransactionItem,
    TransactionsResponse,
    CustomScenarioRequest,
    ForecastDelta,
    CustomScenarioResponse,
)

# Xero schemas
from app.schemas.xero import (
    XeroConnectionStatus,
    XeroAuthUrl,
    XeroCallbackRequest,
    XeroTokenResponse,
    XeroSyncRequest,
    XeroSyncResult,
    XeroInvoiceSummary,
    XeroContactSummary,
    XeroBankTransactionSummary,
    XeroOrganisation,
)

# User config schemas
from app.schemas.user_config import (
    UserConfigurationBase,
    UserConfigurationCreate,
    UserConfigurationUpdate,
    UserConfigurationResponse,
    UserConfigurationWithDefaults,
)

# Scenario schemas
from app.schemas.scenario import (
    FinancialRuleCreate,
    FinancialRuleUpdate,
    FinancialRuleResponse,
    ScenarioCreate,
    ScenarioUpdate,
    ScenarioResponse,
    CustomScenarioCreate,
    ForecastDeltaItem,
    RuleEvaluationResponse,
    ScenarioForecastResponse,
    ScenarioLayerAdd,
    SuggestedDependentScenario,
    ScenarioComparisonResponse,
    ScenarioEventDetail,
    ScenarioLayerResponse,
    PaymentDelayParams,
    ClientLossParams,
    ClientGainParams,
    ClientChangeParams,
    HiringParams,
    FiringParams,
    ContractorChangeParams,
    ExpenseChangeParams,
    DecisionSignal,
)

# Action schemas
from app.schemas.action import (
    ActionOptionResponse,
    EntityLink,
    ActionCardResponse,
    ActionQueueResponse,
    ApproveActionRequest,
    MarkExecutedRequest,
    SkipActionRequest,
    OverrideActionRequest,
    ExecutionArtifactsResponse,
    RecentActivityResponse,
    AgentActivityResponse,
)

# Detection/Alert schemas
from app.schemas.detection import (
    RiskSeverity,
    RiskStatus,
    ControlState,
    ActionStepOwner,
    ActionStepStatus,
    ActionStepResponse,
    RejectedSuggestionResponse,
    RiskResponse,
    ControlResponse,
    RisksListResponse,
    ControlsListResponse,
    ControlsForRiskResponse,
    RisksForControlResponse,
    UpdateControlStateRequest,
    ApproveControlRequest,
    RejectControlRequest,
    CompleteControlRequest,
    SuccessResponse,
    ControlUpdateResponse,
)

# TAMI schemas
from app.schemas.tami import (
    TAMIMode,
    SuggestedAction,
    UIHints,
    TAMIResponse,
    ChatMessage,
    PageContext,
    ChatRequest,
    ChatResponse,
    ScenarioLayerCreate,
    ScenarioLayerIterate,
    ScenarioLayerDiscard,
    GoalPlanRequest,
    GoalPlanResponse,
    ForecastWeekSummary,
    RuleStatus,
    ActiveScenarioSummary,
    CurrentScenarioContext,
    TriggeredScenarioSummary,
    BehaviorInsightsSummary,
    BusinessProfileSummary,
    AlertSummary,
    ContextPayload,
)

# Health schemas
from app.schemas.health import (
    HealthRingData,
    ObligationsStatus,
    ReceivablesStatus,
    ObligationsHealthData,
    ReceivablesHealthData,
    HealthMetricsResponse,
)

# Reconciliation schemas
from app.schemas.reconciliation import (
    ReconciliationSuggestion,
    ReconciliationSuggestionList,
    ReconciliationMatch,
    ApproveReconciliationRequest,
    BulkReconciliationRequest,
    BulkReconciliationResult,
    RejectReconciliationRequest,
    RevertReconciliationRequest,
    ForecastImpactItem,
    ForecastImpactSummary,
    ReconciliationSettings,
    ReconciliationSettingsUpdate,
    ReconciliationQueueSummary,
)

__all__ = [
    # Auth
    "Industry",
    "ProfessionalSubcategory",
    "RevenueRange",
    "Currency",
    "SignupRequest",
    "LoginRequest",
    "UserAuthInfo",
    "DemoLoginRequest",
    "AuthResponse",
    "ForgotPasswordRequest",
    "ForgotPasswordResponse",
    "ResetPasswordRequest",
    "ChangePasswordRequest",
    "BusinessProfileRequest",
    "BusinessProfileResponse",
    # User
    "UserCreate",
    "UserResponse",
    # Treasury
    "CashAccountCreate",
    "CashAccountResponse",
    "CashPositionCreate",
    "CashAccountsUpdate",
    "CashPositionResponse",
    "ClientCreate",
    "ClientResponse",
    "ClientUpdate",
    "ClientCreateForOnboarding",
    "ClientWithEventsResponse",
    "ExpenseBucketCreate",
    "ExpenseBucketResponse",
    "ExpenseBucketUpdate",
    "ExpenseBucketCreateForOnboarding",
    "ExpenseBucketWithEventsResponse",
    # Obligation
    "ObligationAgreementCreate",
    "ObligationAgreementUpdate",
    "ObligationAgreementResponse",
    "ObligationScheduleCreate",
    "ObligationScheduleUpdate",
    "ObligationScheduleResponse",
    "PaymentEventCreate",
    "PaymentEventUpdate",
    "PaymentEventResponse",
    "ObligationWithSchedules",
    "ObligationWithPayments",
    "ObligationFull",
    # Forecast
    "ForecastEventSummary",
    "ConfidenceBreakdown",
    "WeekConfidenceBreakdown",
    "WeekForecast",
    "ForecastSummary",
    "ConfidenceCountBreakdown",
    "ForecastConfidence",
    "ForecastResponse",
    "ForecastResponseV1",
    "MetricValue",
    "ScenarioBarMetrics",
    "ScenarioBarResponse",
    "TransactionItem",
    "TransactionsResponse",
    "CustomScenarioRequest",
    "ForecastDelta",
    "CustomScenarioResponse",
    # Xero
    "XeroConnectionStatus",
    "XeroAuthUrl",
    "XeroCallbackRequest",
    "XeroTokenResponse",
    "XeroSyncRequest",
    "XeroSyncResult",
    "XeroInvoiceSummary",
    "XeroContactSummary",
    "XeroBankTransactionSummary",
    "XeroOrganisation",
    # User config
    "UserConfigurationBase",
    "UserConfigurationCreate",
    "UserConfigurationUpdate",
    "UserConfigurationResponse",
    "UserConfigurationWithDefaults",
    # Scenario
    "FinancialRuleCreate",
    "FinancialRuleUpdate",
    "FinancialRuleResponse",
    "ScenarioCreate",
    "ScenarioUpdate",
    "ScenarioResponse",
    "CustomScenarioCreate",
    "ForecastDeltaItem",
    "RuleEvaluationResponse",
    "ScenarioForecastResponse",
    "ScenarioLayerAdd",
    "SuggestedDependentScenario",
    "ScenarioComparisonResponse",
    "ScenarioEventDetail",
    "ScenarioLayerResponse",
    "PaymentDelayParams",
    "ClientLossParams",
    "ClientGainParams",
    "ClientChangeParams",
    "HiringParams",
    "FiringParams",
    "ContractorChangeParams",
    "ExpenseChangeParams",
    "DecisionSignal",
    # Action
    "ActionOptionResponse",
    "EntityLink",
    "ActionCardResponse",
    "ActionQueueResponse",
    "ApproveActionRequest",
    "MarkExecutedRequest",
    "SkipActionRequest",
    "OverrideActionRequest",
    "ExecutionArtifactsResponse",
    "RecentActivityResponse",
    "AgentActivityResponse",
    # Detection
    "RiskSeverity",
    "RiskStatus",
    "ControlState",
    "ActionStepOwner",
    "ActionStepStatus",
    "ActionStepResponse",
    "RejectedSuggestionResponse",
    "RiskResponse",
    "ControlResponse",
    "RisksListResponse",
    "ControlsListResponse",
    "ControlsForRiskResponse",
    "RisksForControlResponse",
    "UpdateControlStateRequest",
    "ApproveControlRequest",
    "RejectControlRequest",
    "CompleteControlRequest",
    "SuccessResponse",
    "ControlUpdateResponse",
    # TAMI
    "TAMIMode",
    "SuggestedAction",
    "UIHints",
    "TAMIResponse",
    "ChatMessage",
    "PageContext",
    "ChatRequest",
    "ChatResponse",
    "ScenarioLayerCreate",
    "ScenarioLayerIterate",
    "ScenarioLayerDiscard",
    "GoalPlanRequest",
    "GoalPlanResponse",
    "ForecastWeekSummary",
    "RuleStatus",
    "ActiveScenarioSummary",
    "CurrentScenarioContext",
    "TriggeredScenarioSummary",
    "BehaviorInsightsSummary",
    "BusinessProfileSummary",
    "AlertSummary",
    "ContextPayload",
    # Health
    "HealthRingData",
    "ObligationsStatus",
    "ReceivablesStatus",
    "ObligationsHealthData",
    "ReceivablesHealthData",
    "HealthMetricsResponse",
    # Reconciliation
    "ReconciliationSuggestion",
    "ReconciliationSuggestionList",
    "ReconciliationMatch",
    "ApproveReconciliationRequest",
    "BulkReconciliationRequest",
    "BulkReconciliationResult",
    "RejectReconciliationRequest",
    "RevertReconciliationRequest",
    "ForecastImpactItem",
    "ForecastImpactSummary",
    "ReconciliationSettings",
    "ReconciliationSettingsUpdate",
    "ReconciliationQueueSummary",
]
